### PR TITLE
Add ppc64le support.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
There is some license confusion here: The source repository has `COPYING` as a symlink in the repo (not an actual license). The tarball has `COPYING` with the text of GPLv3. However, the `COPYRIGHT` file says that the source code is offered as GPLv2 or later. The `LICENSE` file exists in the repo with the text of GPLv2 but that file is not in the tarball.

I am going to leave the license SPDX identifier as `GPL-2.0-or-later`.

**Comment by bdice** [comment]
@ChristopherHogan @oskooi This PR is ready to review.

**Comment by ChristopherHogan** [comment]
Looks good 👍

**Pull request merged**
